sonar.projectKey=RominaRamon10_PracticoSonarQube
sonar.organization=rominaramon10

# Nombre que se muestra en SonarCloud
sonar.projectName=PracticoSonarQube

# Qué analizar (relativo a este archivo)
sonar.sources=.
sonar.exclusions=**/*test*/**

sonar.sourceEncoding=UTF-8
